package(default_visibility = [
    "//visibility:public",
])

cc_library(
    name = "altazimuth",
    srcs = ["altazimuth.cpp"],
    hdrs = ["altazimuth.h"],
    deps = [
        "//mediapipe/framework/port:opencv_highgui",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:opencv_imgcodecs",
    ],
)