package(default_visibility = [
    "//visibility:public",
])

cc_library(
    name = "hand_tracking",
    srcs = ["hand_tracking.cpp"],
    hdrs = ["hand_tracking.h"],
    deps = [
        "//mediapipe/examples/desktop/controle_module/mediapipe_hands_detector:mediapipe_hands_detector",
        "//mediapipe/examples/desktop/controle_module/neural_network:neural_network",
    ],
)